insert into user (id, username, gender, name, age, balance) values (1, 'account1', 1, '张三', 20, 100.00);
insert into user (id, username, gender, name, age, balance) values (2, 'account2', 1, '李四', 28, 180.00);
insert into user (id, username, gender, name, age, balance) values (3, 'account3', 1, '王五', 32, 280.00);
insert into user (id, username, gender, name, age, balance) values (4, 'Junqing',1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (5, 'Jake'   ,1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (6, 'Sunny'  ,2,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (7, 'Maik'   ,1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (8, 'Zichun' ,1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (9, 'Will'   ,1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (10, 'Jonnie' ,1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (11, 'Yuanyuan',2,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (12, 'Jole'   ,1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (13, 'Ricardo',1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (14, 'Jeremy' ,1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (15, 'Rui'    ,1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (16, 'Peter'  ,1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (17, 'Kyrie'  ,1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (18, 'Ce'     ,1,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (19, 'Lindsey',2,'',18,100.00);
insert into user (id, username, gender, name, age, balance) values (20, 'Shihao' ,1,'',18,100.00);
insert into cool_name (id, gender, name) values (1, 1,'蕭峰');
insert into cool_name (id, gender, name) values (2, 1,'虛竹');
insert into cool_name (id, gender, name) values (3, 1,'段譽');
insert into cool_name (id, gender, name) values (4, 1,'令狐冲');
insert into cool_name (id, gender, name) values (5, 1,'楊過');
insert into cool_name (id, gender, name) values (6, 1,'蝙蝠俠');
insert into cool_name (id, gender, name) values (7, 1,'美隊');
insert into cool_name (id, gender, name) values (8, 1,'螞人');
insert into cool_name (id, gender, name) values (9, 1,'鋼鐵俠');
insert into cool_name (id, gender, name) values (10, 2,'王語嫣');
insert into cool_name (id, gender, name) values (11, 2,'阿朱');
insert into cool_name (id, gender, name) values (12, 2,'任盈盈');